# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dataWindow(object):
    def setupUi(self, dataWindow):
        dataWindow.setObjectName("dataWindow")
        dataWindow.resize(644, 352)
        self.gridLayout_2 = QtWidgets.QGridLayout(dataWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton11 = QtWidgets.QPushButton(dataWindow)
        self.pushButton11.setObjectName("pushButton11")
        self.horizontalLayout_12.addWidget(self.pushButton11)
        self.pushButton22 = QtWidgets.QPushButton(dataWindow)
        self.pushButton22.setObjectName("pushButton22")
        self.horizontalLayout_12.addWidget(self.pushButton22)
        self.pushButton33 = QtWidgets.QPushButton(dataWindow)
        self.pushButton33.setObjectName("pushButton33")
        self.horizontalLayout_12.addWidget(self.pushButton33)
        self.pushButton44 = QtWidgets.QPushButton(dataWindow)
        self.pushButton44.setObjectName("pushButton44")
        self.horizontalLayout_12.addWidget(self.pushButton44)
        self.pushButton55 = QtWidgets.QPushButton(dataWindow)
        self.pushButton55.setObjectName("pushButton55")
        self.horizontalLayout_12.addWidget(self.pushButton55)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label = QtWidgets.QLabel(dataWindow)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_2 = QtWidgets.QLabel(dataWindow)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.pushButtonx11 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx11.setText("")
        self.pushButtonx11.setObjectName("pushButtonx11")
        self.horizontalLayout_10.addWidget(self.pushButtonx11)
        self.pushButtonx12 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx12.setText("")
        self.pushButtonx12.setObjectName("pushButtonx12")
        self.horizontalLayout_10.addWidget(self.pushButtonx12)
        self.pushButtonx13 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx13.setText("")
        self.pushButtonx13.setObjectName("pushButtonx13")
        self.horizontalLayout_10.addWidget(self.pushButtonx13)
        self.pushButtonx14 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx14.setText("")
        self.pushButtonx14.setObjectName("pushButtonx14")
        self.horizontalLayout_10.addWidget(self.pushButtonx14)
        self.pushButtonx15 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx15.setText("")
        self.pushButtonx15.setObjectName("pushButtonx15")
        self.horizontalLayout_10.addWidget(self.pushButtonx15)
        self.pushButtonx16 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx16.setText("")
        self.pushButtonx16.setObjectName("pushButtonx16")
        self.horizontalLayout_10.addWidget(self.pushButtonx16)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(dataWindow)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.pushButtonx21 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx21.setText("")
        self.pushButtonx21.setObjectName("pushButtonx21")
        self.horizontalLayout_9.addWidget(self.pushButtonx21)
        self.pushButtonx22 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx22.setText("")
        self.pushButtonx22.setObjectName("pushButtonx22")
        self.horizontalLayout_9.addWidget(self.pushButtonx22)
        self.pushButtonx23 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx23.setText("")
        self.pushButtonx23.setObjectName("pushButtonx23")
        self.horizontalLayout_9.addWidget(self.pushButtonx23)
        self.pushButtonx24 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx24.setText("")
        self.pushButtonx24.setObjectName("pushButtonx24")
        self.horizontalLayout_9.addWidget(self.pushButtonx24)
        self.pushButtonx25 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx25.setText("")
        self.pushButtonx25.setObjectName("pushButtonx25")
        self.horizontalLayout_9.addWidget(self.pushButtonx25)
        self.pushButtonx26 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx26.setText("")
        self.pushButtonx26.setObjectName("pushButtonx26")
        self.horizontalLayout_9.addWidget(self.pushButtonx26)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(dataWindow)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.pushButtonx31 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx31.setText("")
        self.pushButtonx31.setObjectName("pushButtonx31")
        self.horizontalLayout_8.addWidget(self.pushButtonx31)
        self.pushButtonx32 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx32.setText("")
        self.pushButtonx32.setObjectName("pushButtonx32")
        self.horizontalLayout_8.addWidget(self.pushButtonx32)
        self.pushButtonx33 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx33.setText("")
        self.pushButtonx33.setObjectName("pushButtonx33")
        self.horizontalLayout_8.addWidget(self.pushButtonx33)
        self.pushButtonx34 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx34.setText("")
        self.pushButtonx34.setObjectName("pushButtonx34")
        self.horizontalLayout_8.addWidget(self.pushButtonx34)
        self.pushButtonx35 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx35.setText("")
        self.pushButtonx35.setObjectName("pushButtonx35")
        self.horizontalLayout_8.addWidget(self.pushButtonx35)
        self.pushButtonx36 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx36.setText("")
        self.pushButtonx36.setObjectName("pushButtonx36")
        self.horizontalLayout_8.addWidget(self.pushButtonx36)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(dataWindow)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.pushButtonx41 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx41.setText("")
        self.pushButtonx41.setObjectName("pushButtonx41")
        self.horizontalLayout_7.addWidget(self.pushButtonx41)
        self.pushButtonx42 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx42.setText("")
        self.pushButtonx42.setObjectName("pushButtonx42")
        self.horizontalLayout_7.addWidget(self.pushButtonx42)
        self.pushButtonx43 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx43.setText("")
        self.pushButtonx43.setObjectName("pushButtonx43")
        self.horizontalLayout_7.addWidget(self.pushButtonx43)
        self.pushButtonx44 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx44.setText("")
        self.pushButtonx44.setObjectName("pushButtonx44")
        self.horizontalLayout_7.addWidget(self.pushButtonx44)
        self.pushButtonx45 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx45.setText("")
        self.pushButtonx45.setObjectName("pushButtonx45")
        self.horizontalLayout_7.addWidget(self.pushButtonx45)
        self.pushButtonx46 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx46.setText("")
        self.pushButtonx46.setObjectName("pushButtonx46")
        self.horizontalLayout_7.addWidget(self.pushButtonx46)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(dataWindow)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.pushButtonx51 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx51.setText("")
        self.pushButtonx51.setObjectName("pushButtonx51")
        self.horizontalLayout_6.addWidget(self.pushButtonx51)
        self.pushButtonx52 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx52.setText("")
        self.pushButtonx52.setObjectName("pushButtonx52")
        self.horizontalLayout_6.addWidget(self.pushButtonx52)
        self.pushButtonx53 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx53.setText("")
        self.pushButtonx53.setObjectName("pushButtonx53")
        self.horizontalLayout_6.addWidget(self.pushButtonx53)
        self.pushButtonx54 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx54.setText("")
        self.pushButtonx54.setObjectName("pushButtonx54")
        self.horizontalLayout_6.addWidget(self.pushButtonx54)
        self.pushButtonx55 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx55.setText("")
        self.pushButtonx55.setObjectName("pushButtonx55")
        self.horizontalLayout_6.addWidget(self.pushButtonx55)
        self.pushButtonx56 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx56.setText("")
        self.pushButtonx56.setObjectName("pushButtonx56")
        self.horizontalLayout_6.addWidget(self.pushButtonx56)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(dataWindow)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.pushButtonx61 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx61.setText("")
        self.pushButtonx61.setObjectName("pushButtonx61")
        self.horizontalLayout_2.addWidget(self.pushButtonx61)
        self.pushButtonx62 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx62.setText("")
        self.pushButtonx62.setObjectName("pushButtonx62")
        self.horizontalLayout_2.addWidget(self.pushButtonx62)
        self.pushButtonx63 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx63.setText("")
        self.pushButtonx63.setObjectName("pushButtonx63")
        self.horizontalLayout_2.addWidget(self.pushButtonx63)
        self.pushButtonx64 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx64.setText("")
        self.pushButtonx64.setObjectName("pushButtonx64")
        self.horizontalLayout_2.addWidget(self.pushButtonx64)
        self.pushButtonx65 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx65.setText("")
        self.pushButtonx65.setObjectName("pushButtonx65")
        self.horizontalLayout_2.addWidget(self.pushButtonx65)
        self.pushButtonx66 = QtWidgets.QPushButton(dataWindow)
        self.pushButtonx66.setText("")
        self.pushButtonx66.setObjectName("pushButtonx66")
        self.horizontalLayout_2.addWidget(self.pushButtonx66)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(dataWindow)
        QtCore.QMetaObject.connectSlotsByName(dataWindow)

    def retranslateUi(self, dataWindow):
        _translate = QtCore.QCoreApplication.translate
        dataWindow.setWindowTitle(_translate("dataWindow", "Dane eksperckie"))
        self.pushButton11.setText(_translate("dataWindow", "Masa Ziarna"))
        self.pushButton22.setText(_translate("dataWindow", "Wydajność mąki"))
        self.pushButton33.setText(_translate("dataWindow", "Tolerancja na zakw."))
        self.pushButton44.setText(_translate("dataWindow", "odp. na choroby"))
        self.pushButton55.setText(_translate("dataWindow", "Tolerancja na temp."))
        self.label_2.setText(_translate("dataWindow", "Nawra:"))
        self.label_3.setText(_translate("dataWindow", "Hezja:"))
        self.label_4.setText(_translate("dataWindow", "Jasna:"))
        self.label_5.setText(_translate("dataWindow", "Vinjett:"))
        self.label_6.setText(_translate("dataWindow", "Zebra:"))
        self.label_7.setText(_translate("dataWindow", "Bryza:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dataWindow = QtWidgets.QWidget()
    ui = Ui_dataWindow()
    ui.setupUi(dataWindow)
    dataWindow.show()
    sys.exit(app.exec_())

