# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(787, 476)
        Form.setMinimumSize(QtCore.QSize(787, 476))
        Form.setMaximumSize(QtCore.QSize(787, 476))
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 771, 461))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label1.setMaximumSize(QtCore.QSize(184, 70))
        self.label1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label1.setWordWrap(False)
        self.label1.setObjectName("label1")
        self.verticalLayout_13.addWidget(self.label1)
        self.opis1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.opis1.setMaximumSize(QtCore.QSize(184, 26))
        self.opis1.setText("")
        self.opis1.setObjectName("opis1")
        self.verticalLayout_13.addWidget(self.opis1)
        self.horizontalSlider1 = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.horizontalSlider1.setMouseTracking(False)
        self.horizontalSlider1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalSlider1.setToolTip("")
        self.horizontalSlider1.setStatusTip("")
        self.horizontalSlider1.setWhatsThis("")
        self.horizontalSlider1.setAutoFillBackground(False)
        self.horizontalSlider1.setMinimum(1)
        self.horizontalSlider1.setMaximum(9)
        self.horizontalSlider1.setSingleStep(1)
        self.horizontalSlider1.setPageStep(10)
        self.horizontalSlider1.setProperty("value", 5)
        self.horizontalSlider1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider1.setInvertedAppearance(False)
        self.horizontalSlider1.setInvertedControls(False)
        self.horizontalSlider1.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider1.setTickInterval(1)
        self.horizontalSlider1.setObjectName("horizontalSlider1")
        self.verticalLayout_13.addWidget(self.horizontalSlider1)
        self.opis2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.opis2.setMaximumSize(QtCore.QSize(184, 26))
        self.opis2.setText("")
        self.opis2.setObjectName("opis2")
        self.verticalLayout_13.addWidget(self.opis2)
        self.horizontalSlider2 = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.horizontalSlider2.setMouseTracking(False)
        self.horizontalSlider2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalSlider2.setToolTip("")
        self.horizontalSlider2.setStatusTip("")
        self.horizontalSlider2.setWhatsThis("")
        self.horizontalSlider2.setAutoFillBackground(False)
        self.horizontalSlider2.setMinimum(1)
        self.horizontalSlider2.setMaximum(9)
        self.horizontalSlider2.setSingleStep(1)
        self.horizontalSlider2.setPageStep(10)
        self.horizontalSlider2.setProperty("value", 5)
        self.horizontalSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider2.setInvertedAppearance(False)
        self.horizontalSlider2.setInvertedControls(False)
        self.horizontalSlider2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider2.setTickInterval(1)
        self.horizontalSlider2.setObjectName("horizontalSlider2")
        self.verticalLayout_13.addWidget(self.horizontalSlider2)
        self.opis3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.opis3.setMaximumSize(QtCore.QSize(184, 26))
        self.opis3.setText("")
        self.opis3.setObjectName("opis3")
        self.verticalLayout_13.addWidget(self.opis3)
        self.horizontalSlider3 = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.horizontalSlider3.setMouseTracking(False)
        self.horizontalSlider3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalSlider3.setToolTip("")
        self.horizontalSlider3.setStatusTip("")
        self.horizontalSlider3.setWhatsThis("")
        self.horizontalSlider3.setAutoFillBackground(False)
        self.horizontalSlider3.setMinimum(1)
        self.horizontalSlider3.setMaximum(9)
        self.horizontalSlider3.setSingleStep(1)
        self.horizontalSlider3.setPageStep(10)
        self.horizontalSlider3.setProperty("value", 5)
        self.horizontalSlider3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider3.setInvertedAppearance(False)
        self.horizontalSlider3.setInvertedControls(False)
        self.horizontalSlider3.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider3.setTickInterval(1)
        self.horizontalSlider3.setObjectName("horizontalSlider3")
        self.verticalLayout_13.addWidget(self.horizontalSlider3)
        self.opis4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.opis4.setMaximumSize(QtCore.QSize(184, 26))
        self.opis4.setText("")
        self.opis4.setObjectName("opis4")
        self.verticalLayout_13.addWidget(self.opis4)
        self.horizontalSlider4 = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.horizontalSlider4.setMouseTracking(False)
        self.horizontalSlider4.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalSlider4.setToolTip("")
        self.horizontalSlider4.setStatusTip("")
        self.horizontalSlider4.setWhatsThis("")
        self.horizontalSlider4.setAutoFillBackground(False)
        self.horizontalSlider4.setMinimum(1)
        self.horizontalSlider4.setMaximum(9)
        self.horizontalSlider4.setSingleStep(1)
        self.horizontalSlider4.setPageStep(10)
        self.horizontalSlider4.setProperty("value", 5)
        self.horizontalSlider4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider4.setInvertedAppearance(False)
        self.horizontalSlider4.setInvertedControls(False)
        self.horizontalSlider4.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider4.setTickInterval(1)
        self.horizontalSlider4.setObjectName("horizontalSlider4")
        self.verticalLayout_13.addWidget(self.horizontalSlider4)
        self.opis5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.opis5.setMaximumSize(QtCore.QSize(184, 26))
        self.opis5.setText("")
        self.opis5.setObjectName("opis5")
        self.verticalLayout_13.addWidget(self.opis5)
        self.horizontalSlider5 = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.horizontalSlider5.setMouseTracking(False)
        self.horizontalSlider5.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalSlider5.setToolTip("")
        self.horizontalSlider5.setStatusTip("")
        self.horizontalSlider5.setWhatsThis("")
        self.horizontalSlider5.setAutoFillBackground(False)
        self.horizontalSlider5.setMinimum(1)
        self.horizontalSlider5.setMaximum(9)
        self.horizontalSlider5.setSingleStep(1)
        self.horizontalSlider5.setPageStep(10)
        self.horizontalSlider5.setProperty("value", 5)
        self.horizontalSlider5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider5.setInvertedAppearance(False)
        self.horizontalSlider5.setInvertedControls(False)
        self.horizontalSlider5.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider5.setTickInterval(1)
        self.horizontalSlider5.setObjectName("horizontalSlider5")
        self.verticalLayout_13.addWidget(self.horizontalSlider5)
        self.button1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button1.setMinimumSize(QtCore.QSize(0, 40))
        self.button1.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.button1.setObjectName("button1")
        self.verticalLayout_13.addWidget(self.button1)
        self.horizontalLayout_6.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label2.setMaximumSize(QtCore.QSize(184, 70))
        self.label2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label2.setWordWrap(False)
        self.label2.setObjectName("label2")
        self.verticalLayout_12.addWidget(self.label2)
        self.opis6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.opis6.setMaximumSize(QtCore.QSize(184, 26))
        self.opis6.setText("")
        self.opis6.setObjectName("opis6")
        self.verticalLayout_12.addWidget(self.opis6)
        self.horizontalSlider6 = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.horizontalSlider6.setMouseTracking(False)
        self.horizontalSlider6.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalSlider6.setToolTip("")
        self.horizontalSlider6.setStatusTip("")
        self.horizontalSlider6.setWhatsThis("")
        self.horizontalSlider6.setAutoFillBackground(False)
        self.horizontalSlider6.setMinimum(1)
        self.horizontalSlider6.setMaximum(9)
        self.horizontalSlider6.setSingleStep(1)
        self.horizontalSlider6.setPageStep(10)
        self.horizontalSlider6.setProperty("value", 5)
        self.horizontalSlider6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider6.setInvertedAppearance(False)
        self.horizontalSlider6.setInvertedControls(False)
        self.horizontalSlider6.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider6.setTickInterval(1)
        self.horizontalSlider6.setObjectName("horizontalSlider6")
        self.verticalLayout_12.addWidget(self.horizontalSlider6)
        self.opis7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.opis7.setMaximumSize(QtCore.QSize(184, 26))
        self.opis7.setText("")
        self.opis7.setObjectName("opis7")
        self.verticalLayout_12.addWidget(self.opis7)
        self.horizontalSlider7 = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.horizontalSlider7.setMouseTracking(False)
        self.horizontalSlider7.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalSlider7.setToolTip("")
        self.horizontalSlider7.setStatusTip("")
        self.horizontalSlider7.setWhatsThis("")
        self.horizontalSlider7.setAutoFillBackground(False)
        self.horizontalSlider7.setMinimum(1)
        self.horizontalSlider7.setMaximum(9)
        self.horizontalSlider7.setSingleStep(1)
        self.horizontalSlider7.setPageStep(10)
        self.horizontalSlider7.setProperty("value", 5)
        self.horizontalSlider7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider7.setInvertedAppearance(False)
        self.horizontalSlider7.setInvertedControls(False)
        self.horizontalSlider7.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider7.setTickInterval(1)
        self.horizontalSlider7.setObjectName("horizontalSlider7")
        self.verticalLayout_12.addWidget(self.horizontalSlider7)
        self.opis8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.opis8.setMaximumSize(QtCore.QSize(184, 26))
        self.opis8.setText("")
        self.opis8.setObjectName("opis8")
        self.verticalLayout_12.addWidget(self.opis8)
        self.horizontalSlider8 = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.horizontalSlider8.setMouseTracking(False)
        self.horizontalSlider8.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalSlider8.setToolTip("")
        self.horizontalSlider8.setStatusTip("")
        self.horizontalSlider8.setWhatsThis("")
        self.horizontalSlider8.setAutoFillBackground(False)
        self.horizontalSlider8.setMinimum(1)
        self.horizontalSlider8.setMaximum(9)
        self.horizontalSlider8.setSingleStep(1)
        self.horizontalSlider8.setPageStep(10)
        self.horizontalSlider8.setProperty("value", 5)
        self.horizontalSlider8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider8.setInvertedAppearance(False)
        self.horizontalSlider8.setInvertedControls(False)
        self.horizontalSlider8.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider8.setTickInterval(1)
        self.horizontalSlider8.setObjectName("horizontalSlider8")
        self.verticalLayout_12.addWidget(self.horizontalSlider8)
        self.opis9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.opis9.setMaximumSize(QtCore.QSize(184, 26))
        self.opis9.setText("")
        self.opis9.setObjectName("opis9")
        self.verticalLayout_12.addWidget(self.opis9)
        self.horizontalSlider9 = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.horizontalSlider9.setMouseTracking(False)
        self.horizontalSlider9.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalSlider9.setToolTip("")
        self.horizontalSlider9.setStatusTip("")
        self.horizontalSlider9.setWhatsThis("")
        self.horizontalSlider9.setAutoFillBackground(False)
        self.horizontalSlider9.setMinimum(1)
        self.horizontalSlider9.setMaximum(9)
        self.horizontalSlider9.setSingleStep(1)
        self.horizontalSlider9.setPageStep(10)
        self.horizontalSlider9.setProperty("value", 5)
        self.horizontalSlider9.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider9.setInvertedAppearance(False)
        self.horizontalSlider9.setInvertedControls(False)
        self.horizontalSlider9.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider9.setTickInterval(1)
        self.horizontalSlider9.setObjectName("horizontalSlider9")
        self.verticalLayout_12.addWidget(self.horizontalSlider9)
        self.opis10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.opis10.setMaximumSize(QtCore.QSize(184, 26))
        self.opis10.setText("")
        self.opis10.setObjectName("opis10")
        self.verticalLayout_12.addWidget(self.opis10)
        self.horizontalSlider10 = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.horizontalSlider10.setMouseTracking(False)
        self.horizontalSlider10.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalSlider10.setToolTip("")
        self.horizontalSlider10.setStatusTip("")
        self.horizontalSlider10.setWhatsThis("")
        self.horizontalSlider10.setAutoFillBackground(False)
        self.horizontalSlider10.setMinimum(1)
        self.horizontalSlider10.setMaximum(9)
        self.horizontalSlider10.setSingleStep(1)
        self.horizontalSlider10.setPageStep(10)
        self.horizontalSlider10.setProperty("value", 5)
        self.horizontalSlider10.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider10.setInvertedAppearance(False)
        self.horizontalSlider10.setInvertedControls(False)
        self.horizontalSlider10.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider10.setTickInterval(1)
        self.horizontalSlider10.setObjectName("horizontalSlider10")
        self.verticalLayout_12.addWidget(self.horizontalSlider10)
        self.button2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button2.setMinimumSize(QtCore.QSize(0, 40))
        self.button2.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.button2.setObjectName("button2")
        self.verticalLayout_12.addWidget(self.button2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_9.addItem(spacerItem)
        self.label_pic2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_pic2.setMaximumSize(QtCore.QSize(380, 194))
        self.label_pic2.setObjectName("label_pic2")
        self.verticalLayout_9.addWidget(self.label_pic2)
        self.verticalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_pic1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_pic1.setMaximumSize(QtCore.QSize(380, 252))
        self.label_pic1.setObjectName("label_pic1")
        self.verticalLayout_8.addWidget(self.label_pic1)
        self.verticalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "AWD"))
        self.label1.setText(_translate("Form", "pic"))
        self.button1.setText(_translate("Form", "Oblicz"))
        self.label2.setText(_translate("Form", "pic"))
        self.button2.setText(_translate("Form", "Dane eksperckie"))
        self.label_pic2.setText(_translate("Form", "pic"))
        self.label_pic1.setText(_translate("Form", "pic"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

